### PR TITLE
Small fixes for non-windows users.

### PR DESCRIPTION
**Pull request by Arctize**

### CODE REVIEW

**Comment by stendarr** [comment]
this repository will no longer be continued - instead, you are welcome to contribute at *gitlab.ethz.ch/dominik/uebungsscraper*

**Comment by Arctize** [comment]
Saw that, but I get a 404 page not found error at gitlab.ethz.ch/dominik/uebungsscraper, even when logged in with my ETHZ login.

**Comment by stendarr** [comment]
Terribly sorry, repo set to private, try again now.

**Comment by Arctize** [comment]
Alright, opened a pull request over there.

**Pull request closed without merging**
